### ISSUE TITLE
Make $criteria and $orderBy passable to custom method in ResourcesResolver

### ISSUE THREAD

**Issue by tom10271** [Sylius/SyliusResourceBundle#146]
Long long time ago(Really long time ago, like beta stage) it was working

**Describe the proposed solution**

**Describe alternatives you've considered**

**Additional context**

**Comment by tom10271** [comment]
```
store_api_products:
    path: /
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            paginate: 100
            repository:
                method: createFilterPaginator
                arguments:
                    criteria: $criteria # Actually, this line
            sortable: true
            sorting: { createdAt: desc }
            filterable: true
        _groups: [Default, Internal]
```
