### ISSUE TITLE
Configuration override for ressource

### ISSUE THREAD

**Issue by oallain** [Sylius/SyliusResourceBundle#152]
**Sylius version affected**: 1.7.0 (probably all)

**Description**  
Configuration at project level should prevail over configuration at plugin level.

**Steps to reproduce**  
1) Install Sylius/AdminOrderCreationPlugin
```
php bin/console sylius:debug:resource sylius.customer
+--------------------+-----------------------------------------------------------------+
| name               | customer                                                        |
| application        | sylius                                                          |
| driver             | doctrine/orm                                                    |
| classes.model      | App\Entity\Customer\Customer                                    |
| classes.repository | Sylius\AdminOrderCreationPlugin\Doctrine\ORM\CustomerRepository |
| classes.interface  | Sylius\Component\Customer\Model\CustomerInterface               |
| classes.controller | Sylius\Bundle\ResourceBundle\Controller\ResourceController      |
| classes.factory    | Sylius\Component\Resource\Factory\Factory                       |
| classes.form       | Sylius\Bundle\CustomerBundle\Form\Type\CustomerType             |
+--------------------+-----------------------------------------------------------------+
```
Repository used is : Sylius\AdminOrderCreationPlugin\Doctrine\ORM\CustomerRepository

2) Create a CustomerRepository in the projet.
And configure your ressource (in config/packages/_sylius.yaml) :
```yaml
sylius_customer:
    resources:
        customer:
            classes:
                model: App\Entity\Customer\Customer
                repository: App\Entity\Customer\CustomerRepository
```

Then 
```
php bin/console sylius:debug:resource sylius.customer
+--------------------+-----------------------------------------------------------------+
| name               | customer                                                        |
| application        | sylius                                                          |
| driver             | doctrine/orm                                                    |
| classes.model      | App\Entity\Customer\Customer                                    |
| classes.repository | Sylius\AdminOrderCreationPlugin\Doctrine\ORM\CustomerRepository |
| classes.interface  | Sylius\Component\Customer\Model\CustomerInterface               |
| classes.controller | Sylius\Bundle\ResourceBundle\Controller\ResourceController      |
| classes.factory    | Sylius\Component\Resource\Factory\Factory                       |
| classes.form       | Sylius\Bundle\CustomerBundle\Form\Type\CustomerType             |
+--------------------+-----------------------------------------------------------------+
```

**Question**
Do you think it's a bug or I configured something wrong?

Thank you in advance for your help.

**Comment by vvasiloi** [comment]
Just write your config after you import the plugin config.
Example: 
```
// config/packages/sylius_admin_order_creation.yaml
imports:
    - { resource: "@SyliusAdminOrderCreationPlugin/Resources/config/app/config.yml" }

sylius_customer:
    resources:
        customer:
            classes:
                repository: App\Entity\Customer\CustomerRepository
```
Only repository is defined by the plugin: https://github.com/Sylius/AdminOrderCreationPlugin/blob/master/src/Resources/config/app/config.yml#L38
