### ISSUE TITLE
Remove FosRestBundle and BazingaHateoasBundle dependency.

### ISSUE THREAD

**Issue by videni** [Sylius/SyliusResourceBundle#170]
# Reason 1
The two bundles are very usefull to build RESTfull API via HAL,   I also like to support [JSONAPI](https://jsonapi.org/), so I suggest move they into a new package, maybe named as HAL extension for SyliusResourceBundle. 

# Reason 2

I'd like transform my entity to json using [fractal](https://github.com/thephpleague/fractal)  instead of jmsserializer.

even though jmsserializer is flexiable and powerful , but it makes my API not stable enough, because they share the same metadata, for example, someone adds a  'roles'  property to my user class within 'Default' groups.

```
Acme\Component\User\Model\User:
    exclusion_policy: ALL
    xml_root_name: xiaolvmo_user
    properties:
        id:
            expose: true
            type: integer
            groups: [Default]
        username:
            expose: true
            type: string
            groups: [Default]
        roles:
            expose: true
            type: ArrayCollection<Acme\Component\User\Model\Role>
            groups: [Default]

```

if Order also has user relation,  then it will output roles, which may be not what need.   serializing the roles property  may trigger a doctrine/orm lazy loading, which hurt performance. so the API is very fragile because of jmsserializer.
