### ISSUE TITLE
Extend ResourceController

### ISSUE THREAD

**Issue by albanR** [Sylius/SyliusResourceBundle#31]
Hi,

Resource Bundle is really handy and I use it for a resource for which I need to add actions. 

```
sylius_resource:
    dp.geozone:
        driver: doctrine/orm
        classes:
            model: Dp\ShopBundle\Entity\GeoZone
```

When I try to extend ResourceController, I get the error:

```
An exception has been thrown during the rendering of a template ("Warning: Missing
argument 1 for 
Sylius\Bundle\ResourceBundle\Controller\ResourceController::__construct(), 
called in...
```

I registered that service as it's done in Sylius Bundles hoping it would feed the __construct method:

```
<service id="dp.controller.geozone" class="%dp.controller.geozone.class%">
        <argument>dp</argument>
        <argument>geozone</argument>
        <argument>DpShopBundle:GeoZone</argument>
        <call method="setContainer">
            <argument type="service" id="service_container" />
        </call>
</service>
```

but with no luck. What am I missing? Thanks!
