### ISSUE TITLE
Incorrect documentation for overriding the view of a resource form

### ISSUE THREAD

**Issue by DanielCAlex** [Sylius/SyliusResourceBundle#362]
latest

The [config reference](https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/reference.md) suggests to overwrite a resource's form rendering as such
```
sylius_resource:
    resources:
        app.book:
            driver: doctrine/orm
            classes:
            options:
                object_manager: default
            templates:
                form: Book/_form.html.twig
```
However [Configuration.php](https://github.com/Sylius/SyliusResourceBundle/blob/master/src/Bundle/DependencyInjection/Configuration.php) suggests the only acceptable value is a scalar
```
 private function addResourcesSection(ArrayNodeDefinition $node): void
    {
        $node
            ->children()
                ->arrayNode('resources')
                    ->useAttributeAsKey('name')
                    ->arrayPrototype()
                        ->children()
                            ->scalarNode('driver')->defaultValue(SyliusResourceBundle::DRIVER_DOCTRINE_ORM)->end()
                            ->variableNode('options')->end()
                            ->scalarNode('templates')->cannotBeEmpty()->end()
```
So when I configure:
```
sylius_resource:
  resources:
etc etc etc
      templates:
        form: Admin/Ruleset/_form.html.twig
```
I get:
`Invalid type for path "sylius_resource.resources.skyboundtech.wholesale_ruleset.templates". Expected "scalar", but got "array".`
