### ISSUE TITLE
Getting resources via criterias and findBy

### ISSUE THREAD

**Issue by jjanvier** [Sylius/SyliusResourceBundle#40]
I tried to use `findBy` instead of `createFilterPaginator` in the product backend. Here is my conf : 

``` yaml
sylius_backend_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            paginate: false
            method: findBy
            arguments: [$criteria, $sorting]
        criteria: {}
        sorting: { createdAt: desc }
```

When submitting a request to findBy via the product filter form, I get the following exception : 

``` php
[Semantical Error] line 0, col 107 near 'sku = :sku ORDER': Error: Class Sylius\Bundle\CoreBundle\Entity\Product has no field or association named sku 
```
