### ISSUE TITLE
Sorting links are broken when a defaut sorting config is defined for the resource

### ISSUE THREAD

**Issue by jjanvier** [Sylius/SyliusResourceBundle#42]
For example, in the product BO. With the default resource config no sorting links appear. With this config, it works : 

``` yaml
sylius_backend_product_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.product:indexAction
        _sylius:
            template: SyliusWebBundle:Backend/Product:index.html.twig
            method: createFilterPaginator
            arguments: [$criteria]
        criteria: {}
```
