### ISSUE TITLE
[Enhancement] adding a special filter criteria : _app.user

### ISSUE THREAD

**Issue by jjanvier** [Sylius/SyliusResourceBundle#43]
Hi guys,

While coding the my account order section, I'm facing a problem. I need to filter orders that belongs to the current user. Of course, I could do it by writing a custom action in a controller... But the `listAction` of the `ResourceBundle` does 90% of what I need, except filtering orders with the current logged user.

Could we introduce a special criteria for filtering a resources linked to the current user ? Does it make sense in this bundle ?

What I need would be something like 

``` yaml
sylius_account_order_index:
    pattern: /account/orders
    methods: [GET]
    defaults:
        _controller: app.controller.order:indexAction
        _sylius:
            criteria:
                user: _app.user
```
