### ISSUE TITLE
App\Repository\BookRepository::__construct(): Argument #1 ($registry) must be of type Doctrine\Persistence\ManagerRegistry, ContainerLqboKUT\EntityManagerGhost51e8656 given

### ISSUE THREAD

**Issue by Stanzi1791** [Sylius/SyliusResourceBundle#548]
**Sylius version affected**: SyliusResourceBundle version 1.10.1

**Description**  
I've been trying to create a Book class and have SyliusResourceBundle generate routes for it, as in the documentation here:
https://github.com/Sylius/SyliusResourceBundle/blob/1.11/docs/configuration.md

Its giving me the following error:

`App\Repository\BookRepository::__construct(): Argument #1 ($registry) must be of type Doctrine\Persistence\ManagerRegistry, ContainerTZ2CpKX\EntityManagerGhost51e8656 given, called in C:\xampp\htdocs\sylius\my_project_directory\var\cache\dev\ContainerTZ2CpKX\getApp_Repository_BookService.php on line 34`

![image](https://user-images.githubusercontent.com/6654587/210223827-acc1a31f-d475-42c8-a2b0-7da005fc7268.png)

**Steps to reproduce**  
- Start with a fresh Symfony installation: `symfony new my_project_directory --version="6.2.*" --webapp`
- Add SyliusResourceBundle: `composer require sylius/resource-bundle -W`
- Create "Book" entity with Symfony maker bundle, as described here: https://docs.sylius.com/en/latest/cookbook/entities/custom-model.html
- Book implements ResourceInterface:

```
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\ORM\Mapping as ORM;
use Sylius\Component\Resource\Model\ResourceInterface;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book implements ResourceInterface
{

// ...
```

- BookRepository implements RepositoryInterface and uses ResourceRepositoryTrait:

```
<?php

namespace App\Repository;

use App\Entity\Book;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Sylius\Bundle\ResourceBundle\Doctrine\ORM\ResourceRepositoryTrait;
use Sylius\Component\Resource\Repository\RepositoryInterface;

/**
 * @extends ServiceEntityRepository<Book>
 *
 * @method Book|null find($id, $lockMode = null, $lockVersion = null)
 * @method Book|null findOneBy(array $criteria, array $orderBy = null)
 * @method Book[]    findAll()
 * @method Book[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class BookRepository extends ServiceEntityRepository implements RepositoryInterface
{
    use ResourceRepositoryTrait;

    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Book::class);
    }

// ...
```

- Update `config/packages/sylius_resource.yaml`:

```
# @see https://github.com/Sylius/SyliusResourceBundle/blob/master/docs/index.md
sylius_resource:
    # Override default settings
    #settings:

    # Configure your resources
    resources:
        app.book:
            classes:
                model: App\Entity\Book
                repository: App\Repository\BookRepository
```
- Update `config/routes.yaml`:

```
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_book:
    resource: |
        alias: app.book
    type: sylius.resource
```

- Create database, make and execute migration.
- Start the Symfony webserver and go to `localhost:8000/books`

Leaving out the repository's constructor seems to solve the problem, but the example in the documentation also has a constructor, so I shouldn't need to remove it.

And the documentation here ( https://docs.sylius.com/en/latest/cookbook/entities/custom-model.html ) says the repository should extend `EntityRepository` instead of using `RepositoryInterface` + `ResourceRepositoryTrait`, but that gives the same error - unless I leave out the constructor.

**Questions**  
What class should my repository be extending/implementing?
Do I need to remove the repository's constructor?
And if not: how can I fix this error that seems to be caused by the repository's constructor?

**Comment by loic425** [comment]
@ Stanzi1791 
This is already fixed but not released.
for a work around, remove the repository configuration from the resource.

```yaml
sylius_resource:
    resources:
        app.book:
            classes:
                model: App\Entity\Book
                #repository: App\Repository\BookRepository
```
