### ISSUE TITLE
SyliusCrudRoutes attribute and host parameter

### ISSUE THREAD

**Issue by notFloran** [Sylius/SyliusResourceBundle#843]
**Describe the proposed solution**

Allow `host` parameter for `SyliusCrudRoutes` attribute as for  `SyliusRoute` attribute.

**Describe alternatives you've considered**

I use YAML config with the following config.

app.yaml : 

```
app_extranet:
    resource: "_extranet.yaml"
    host: "%extranet_host%"
```

_extranet.yaml : 

```
extranet_my_resource:
    resource: |
        alias: app.chassis
    type: sylius.resource
```
