### ISSUE TITLE
Allow Custom HTTP Methods Configuration for CRUD Actions in Sylius Resource Bundle

### ISSUE THREAD

**Issue by julienromey** [Sylius/SyliusResourceBundle#893]
**Title:** Allow Configuration of HTTP Methods for CRUD Actions in Sylius Resource Bundle

**Description:**

Hello,

I'm experiencing an issue with the Sylius Resource Bundle when configuring CRUD operations. My current setup is:

```yaml
my_entity:
    resource: |
        alias: my_entity
        templates: "@Templates/Folder"
        except: ['show']
    type: sylius.resource
```
For update actions, the my_entity_update route is restricted to GET|PUT|PATCH. However, we are sending POST requests. With Symfony 7, http_method_override will default to false, making this workaround unusable.

Suggestion:

Allow configuration of HTTP methods for CRUD actions in the resource configuration.
Reflect this configuration in the route definitions.
This enhancement will increase flexibility and compatibility with various request methods.

Thank you.
