### ISSUE TITLE
Missing options['object_manager'] in AsResource configuration

### ISSUE THREAD

**Issue by next-sentence** [Sylius/SyliusResourceBundle#947]
With yaml format it is possible to set custom object manager per resourse, like this
```
sylius_resource:
    resources:
        app.book:
            options:
                object_manager: custom
            classes:
                model: App\Entity\Book
```

 but with attributes it is not possible, so you have to duplicate the config
